[{"tags": ["android", "kotlin"], "answers": [{"tags": [], "owner": {"reputation": 816, "user_id": 1254160, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/382f773421a3a63914993ae6d1884558?s=128&d=identicon&r=PG", "display_name": "Ilya Vorobiev", "link": "https://stackoverflow.com/users/1254160/ilya-vorobiev"}, "is_accepted": true, "score": 12, "last_activity_date": 1432096039, "creation_date": 1432096039, "answer_id": 30340268, "question_id": 30339331, "link": "https://stackoverflow.com/questions/30339331/using-kotlin-with-contentresolver-caused-illegalargumentexception/30340268#30340268", "title": "Using kotlin with ContentResolver caused IllegalArgumentException", "body": "<p>By default all the variables and parameters in Kotlin are non-null. You are passing a null parameter to your function. If you want to pass null parameter you need to add <code>?</code> symbol to your parameter's type, like <code>uri: Uri?</code>. But better way is to check if the parameter you want to pass to the function is null and handle this situation.\nFor more information you can check this article <a href=\"http://kotlinlang.org/docs/reference/null-safety.html\" rel=\"noreferrer\">http://kotlinlang.org/docs/reference/null-safety.html</a></p>\n"}, {"tags": [], "owner": {"reputation": 149, "user_id": 8269668, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/7ee99d9374d42c6bffcb4cb72f38e438?s=128&d=identicon&r=PG&f=1", "display_name": "Aleksei Mulin", "link": "https://stackoverflow.com/users/8269668/aleksei-mulin"}, "is_accepted": false, "score": 1, "last_activity_date": 1535371500, "creation_date": 1535371500, "answer_id": 52038973, "question_id": 30339331, "link": "https://stackoverflow.com/questions/30339331/using-kotlin-with-contentresolver-caused-illegalargumentexception/52038973#52038973", "title": "Using kotlin with ContentResolver caused IllegalArgumentException", "body": "<p>Old post but I hope that somebody will find it useful. I bumped into the same exception when migrated my content provider to Kotlin and it was because a cursor factory was null. It's allowed being null in Java and java doc states the same that null is used for the default factory but it's forbidden in Kotlin so I ended-up with creating the custom cursor factory as below:</p>\n\n<pre><code>class DatabaseCursorFactory : SQLiteDatabase.CursorFactory {\n\n    override fun newCursor(db: SQLiteDatabase?, driver: SQLiteCursorDriver?, editTable: String?, query: SQLiteQuery?): Cursor {\n        return SQLiteCursor(driver, editTable, query)\n    }\n}\n</code></pre>\n\n<p>And then used in ContentProvider:</p>\n\n<pre><code>override fun onCreate(): Boolean {\n    mDatabaseOpenHelper = DatabaseOpenHelper(context, DB_NAME, DatabaseCursorFactory(), DB_VERSION)\n    return true\n}\n</code></pre>\n"}], "owner": {"reputation": 43, "user_id": 1260663, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/e02feb7174411f0350263cdac9e4e2b8?s=128&d=identicon&r=PG", "display_name": "Kesco", "link": "https://stackoverflow.com/users/1260663/kesco"}, "delete_vote_count": 0, "reopen_vote_count": 0, "close_vote_count": 0, "is_answered": true, "view_count": 9532, "favorite_count": 0, "accepted_answer_id": 30340268, "answer_count": 2, "score": 3, "last_activity_date": 1535371500, "creation_date": 1432089159, "question_id": 30339331, "link": "https://stackoverflow.com/questions/30339331/using-kotlin-with-contentresolver-caused-illegalargumentexception", "title": "Using kotlin with ContentResolver caused IllegalArgumentException", "body": "<p>I'm try to write an app with Kotlin. I put the contentprovider querying sql on the other process. When querying by ContentResolver in the main process, the App crashed.</p>\n\n<p>The code is:</p>\n\n<pre><code>protected fun select(uri: Uri, sql: String, vararg args: Any): Cursor {\n    val sArgs = Array(args.size(), { i -&gt; lang.String.valueOf(args.get(i)) })\n    return context.getContentResolver().query(uri, null, sql, sArgs, null)\n}\n\npublic fun selectAllAccounts(): Array&lt;Account&gt; {\n    val cursor = select(parseUri(AccountSchema.TABLE_NAME), \"select * from \" + AccountSchema.TABLE_NAME)\n    val accounts = Array(cursor.getCount(), { i -&gt;\n        if (!cursor.moveToPosition(i)) {\n            throw RuntimeException(\"Cursor move failed\")\n        }\n        Account(context, cursor)\n    })\n    return accounts\n}\n</code></pre>\n\n<p>It will throw an IllegalArgumentException:</p>\n\n<pre><code>05-20 10:27:21.120    3337-3337/com.kescoode.yomail E/AndroidRuntime\ufe55 FATAL EXCEPTION: main\nProcess: com.kescoode.yomail, PID: 3337\njava.lang.RuntimeException: Unable to start activity ComponentInfo{com.kescoode.yomail/com.kescoode.yomail.ui.activity.HomeActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter projection\n        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)\n        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)\n        at android.app.ActivityThread.access$800(ActivityThread.java:144)\n        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)\n        at android.os.Handler.dispatchMessage(Handler.java:102)\n        at android.os.Looper.loop(Looper.java:136)\n        at android.app.ActivityThread.main(ActivityThread.java:5146)\n        at java.lang.reflect.Method.invokeNative(Native Method)\n        at java.lang.reflect.Method.invoke(Method.java:515)\n        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)\n        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)\n        at dalvik.system.NativeStart.main(Native Method)\n Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter projection\n        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)\n        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)\n        at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)\n        at android.content.ContentResolver.query(ContentResolver.java:461)\n        at android.content.ContentResolver.query(ContentResolver.java:404)\n        at com.kescoode.yomail.db.Dao.select(internal.kt:33)\n        at com.kescoode.yomail.db.AccountDao.selectAllAccounts(AccountDao.kt:21)\n        at com.kescoode.yomail.App.isLogged(App.kt:28)\n        at com.kescoode.yomail.ui.activity.HomeActivity.onCreate(HomeActivity.kt:17)\n        at android.app.Activity.performCreate(Activity.java:5231)\n        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)\n        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169  \n</code></pre>\n"}, {"tags": ["unit-testing", "kotlin", "testing", "exception", "junit4"], "answers": [{"comments": [{"owner": {"reputation": 1654, "user_id": 2138356, "user_type": "registered", "accept_rate": 88, "profile_image": "https://www.gravatar.com/avatar/b5cfbdd95128b8feefe8c49299022af9?s=128&d=identicon&r=PG", "display_name": "fasth", "link": "https://stackoverflow.com/users/2138356/fasth"}, "edited": false, "score": 0, "creation_date": 1446024077, "post_id": 30333677, "comment_id": 54566469, "body": "<code>javaClass&lt;T&gt;()</code> is deprecated now. Use <code>MyException::class.java</code> instead."}, {"owner": {"reputation": 14571, "user_id": 1542343, "user_type": "registered", "accept_rate": 84, "profile_image": "https://www.gravatar.com/avatar/0c67fc696612cc6c62a17d8bb2fdd17f?s=128&d=identicon&r=PG", "display_name": "gvlasov", "link": "https://stackoverflow.com/users/1542343/gvlasov"}, "edited": false, "score": 1, "creation_date": 1447392301, "post_id": 30333677, "comment_id": 55145196, "body": "failsWith is deprecated, <a href=\"https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.test/assert-fails-with.html\" rel=\"nofollow noreferrer\">assertFailsWith</a> should be used instead."}], "tags": [], "owner": {"reputation": 35078, "user_id": 615306, "user_type": "registered", "accept_rate": 51, "profile_image": "https://www.gravatar.com/avatar/5a11940d70233031c01ead6c0b62c990?s=128&d=identicon&r=PG", "display_name": "Kirill Rakhman", "link": "https://stackoverflow.com/users/615306/kirill-rakhman"}, "is_accepted": false, "score": 26, "last_activity_date": 1495508523, "last_edit_date": 1495508523, "creation_date": 1432061061, "answer_id": 30333677, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/30333677#30333677", "title": "Test expected exceptions in Kotlin", "body": "<p>You can use <code>@Test(expected = ArithmeticException::class)</code> or even better one of Kotlin's library methods like <a href=\"http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.test/fails-with.html\" rel=\"noreferrer\"><code>failsWith()</code></a>.</p>\n\n<p>You can make it even shorter by using reified generics and a helper method like this:</p>\n\n<pre><code>inline fun &lt;reified T : Throwable&gt; failsWithX(noinline block: () -&gt; Any) {\n    kotlin.test.failsWith(javaClass&lt;T&gt;(), block)\n}\n</code></pre>\n\n<p>And example using the annotation:</p>\n\n<pre><code>@Test(expected = ArithmeticException::class)\nfun omg() {\n\n}\n</code></pre>\n"}, {"tags": [], "owner": {"reputation": 235985, "user_id": 252000, "user_type": "registered", "accept_rate": 95, "profile_image": "https://www.gravatar.com/avatar/082b8ee2b0aebb430b8d4d98e6a5c32f?s=128&d=identicon&r=PG", "display_name": "fredoverflow", "link": "https://stackoverflow.com/users/252000/fredoverflow"}, "is_accepted": true, "score": 139, "last_activity_date": 1602792714, "last_edit_date": 1602792714, "creation_date": 1433166686, "answer_id": 30575351, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/30575351#30575351", "title": "Test expected exceptions in Kotlin", "body": "<p>The Kotlin translation of the Java example for <strong>JUnit 4.12</strong> is:</p>\n<pre><code>@Test(expected = ArithmeticException::class)\nfun omg() {\n    val blackHole = 1 / 0\n}\n</code></pre>\n<p>However, <strong>JUnit 4.13</strong> <a href=\"https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md\" rel=\"noreferrer\">introduced</a> two <code>assertThrows</code> methods for finer-granular exception scopes:</p>\n<pre><code>@Test\nfun omg() {\n    // ...\n    assertThrows(ArithmeticException::class.java) {\n        val blackHole = 1 / 0\n    }\n    // ...\n}\n</code></pre>\n<p>Both <code>assertThrows</code> methods return the expected exception for additional assertions:</p>\n<pre><code>@Test\nfun omg() {\n    // ...\n    val exception = assertThrows(ArithmeticException::class.java) {\n        val blackHole = 1 / 0\n    }\n    assertEquals(&quot;/ by zero&quot;, exception.message)\n    // ...\n}\n</code></pre>\n"}, {"comments": [{"owner": {"reputation": 235985, "user_id": 252000, "user_type": "registered", "accept_rate": 95, "profile_image": "https://www.gravatar.com/avatar/082b8ee2b0aebb430b8d4d98e6a5c32f?s=128&d=identicon&r=PG", "display_name": "fredoverflow", "link": "https://stackoverflow.com/users/252000/fredoverflow"}, "edited": false, "score": 1, "creation_date": 1495695592, "post_id": 34556914, "comment_id": 75363474, "body": "If get a 404 on your link, has <code>kotlin.test</code> been replaced by something else?"}, {"owner": {"reputation": 16853, "user_id": 4101725, "user_type": "registered", "profile_image": "https://lh6.googleusercontent.com/-dGwoPMFb_tM/AAAAAAAAAAI/AAAAAAAABks/tMMqc6E9REg/photo.jpg?sz=128", "display_name": "Michele d&#39;Amico", "link": "https://stackoverflow.com/users/4101725/michele-damico"}, "reply_to_user": {"reputation": 235985, "user_id": 252000, "user_type": "registered", "accept_rate": 95, "profile_image": "https://www.gravatar.com/avatar/082b8ee2b0aebb430b8d4d98e6a5c32f?s=128&d=identicon&r=PG", "display_name": "fredoverflow", "link": "https://stackoverflow.com/users/252000/fredoverflow"}, "edited": false, "score": 0, "creation_date": 1495701463, "post_id": 34556914, "comment_id": 75366695, "body": "@fredoverflow No, is not replaced, but just removed from standard libraries. I&#39;ve updated link to github kotlin repository but unfortunately I cannot find any link to documentation. Anyway jar is shipped by kotlin-plugin in intelliJ or you can find it on the net or add maven/grandle dependency to your project."}, {"owner": {"reputation": 2517, "user_id": 4312751, "user_type": "registered", "accept_rate": 57, "profile_image": "https://i.stack.imgur.com/PuJuA.jpg?s=128&g=1", "display_name": "mac229", "link": "https://stackoverflow.com/users/4312751/mac229"}, "edited": false, "score": 8, "creation_date": 1506024365, "post_id": 34556914, "comment_id": 79664885, "body": "compile &quot;org.jetbrains.kotlin:kotlin-test:$kotlin_version&quot;"}, {"owner": {"reputation": 124764, "user_id": 90848, "user_type": "registered", "accept_rate": 90, "profile_image": "https://i.stack.imgur.com/tK3A3.jpg?s=128&g=1", "display_name": "Laurence Gonsalves", "link": "https://stackoverflow.com/users/90848/laurence-gonsalves"}, "reply_to_user": {"reputation": 2517, "user_id": 4312751, "user_type": "registered", "accept_rate": 57, "profile_image": "https://i.stack.imgur.com/PuJuA.jpg?s=128&g=1", "display_name": "mac229", "link": "https://stackoverflow.com/users/4312751/mac229"}, "edited": false, "score": 4, "creation_date": 1521218215, "post_id": 34556914, "comment_id": 85652696, "body": "@mac229 s/compile/testCompile/"}, {"owner": {"reputation": 16853, "user_id": 4101725, "user_type": "registered", "profile_image": "https://lh6.googleusercontent.com/-dGwoPMFb_tM/AAAAAAAAAAI/AAAAAAAABks/tMMqc6E9REg/photo.jpg?sz=128", "display_name": "Michele d&#39;Amico", "link": "https://stackoverflow.com/users/4101725/michele-damico"}, "reply_to_user": {"reputation": 339, "user_id": 7503961, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/5a95a40e910e1160fba61e8bddbe9632?s=128&d=identicon&r=PG&f=1", "display_name": "Ashish Sharma", "link": "https://stackoverflow.com/users/7503961/ashish-sharma"}, "edited": false, "score": 0, "creation_date": 1592375552, "post_id": 34556914, "comment_id": 110399496, "body": "@AshishSharma : <a href=\"https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-fails-with.html\" rel=\"nofollow noreferrer\">kotlinlang.org/api/latest/kotlin.test/kotlin.test/&hellip;</a> assertFailWith return the exception and you can use it to write your own assert."}, {"owner": {"reputation": 339, "user_id": 7503961, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/5a95a40e910e1160fba61e8bddbe9632?s=128&d=identicon&r=PG&f=1", "display_name": "Ashish Sharma", "link": "https://stackoverflow.com/users/7503961/ashish-sharma"}, "edited": false, "score": 0, "creation_date": 1592504958, "post_id": 34556914, "comment_id": 110457493, "body": "I manage to that like below. But If anybody can provide me an example how can i check for exception type in case of completablefutue because it wrapped actual exception class .   var exception =  assertFailsWith(CustomException::class) {             someclass.somemethod(arg)         }         Assertions.assertEquals(&quot;some message&quot;, exception.localizedMessage)"}], "tags": [], "owner": {"reputation": 16853, "user_id": 4101725, "user_type": "registered", "profile_image": "https://lh6.googleusercontent.com/-dGwoPMFb_tM/AAAAAAAAAAI/AAAAAAAABks/tMMqc6E9REg/photo.jpg?sz=128", "display_name": "Michele d&#39;Amico", "link": "https://stackoverflow.com/users/4101725/michele-damico"}, "is_accepted": false, "score": 92, "last_activity_date": 1601981039, "last_edit_date": 1601981039, "creation_date": 1451658084, "answer_id": 34556914, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/34556914#34556914", "title": "Test expected exceptions in Kotlin", "body": "<p><a href=\"https://github.com/JetBrains/kotlin/tree/master/libraries/kotlin.test\" rel=\"noreferrer\">Kotlin has its own test helper package</a> that can help to do this kind of unittest.</p>\n<p>Your test can be very expressive by use <code>assertFailWith</code>:</p>\n<pre><code>@Test\nfun test_arithmethic() {\n    assertFailsWith&lt;ArithmeticException&gt; {\n        omg()\n    }\n}\n</code></pre>\n"}, {"comments": [{"owner": {"reputation": 440, "user_id": 2878706, "user_type": "registered", "profile_image": "https://i.stack.imgur.com/WjIVS.png?s=128&g=1", "display_name": "Ivan Trechyokas", "link": "https://stackoverflow.com/users/2878706/ivan-trechyokas"}, "edited": false, "score": 0, "creation_date": 1541488956, "post_id": 37188436, "comment_id": 93224574, "body": "seems line it doesn&#39;t work in proper way.  I check  1. shouldThrow&lt;java.lang.AssertionError&gt; { someMethod().isOK shouldBe true } - green 2. shouldThrow&lt;java.lang.AssertionError&gt; { someMethod().isOK shouldBe false } - green   someMethod() throw &quot;java.lang.AssertionError: message&quot; when it should, and return object if OK.   In both cases  shouldThrow is green when OK and when NOT."}, {"owner": {"reputation": 14965, "user_id": 2048448, "user_type": "registered", "accept_rate": 82, "profile_image": "https://www.gravatar.com/avatar/9875a5906274bc61f9e3106537a601fc?s=128&d=identicon&r=PG", "display_name": "sksamuel", "link": "https://stackoverflow.com/users/2048448/sksamuel"}, "reply_to_user": {"reputation": 440, "user_id": 2878706, "user_type": "registered", "profile_image": "https://i.stack.imgur.com/WjIVS.png?s=128&g=1", "display_name": "Ivan Trechyokas", "link": "https://stackoverflow.com/users/2878706/ivan-trechyokas"}, "edited": false, "score": 0, "creation_date": 1541577888, "post_id": 37188436, "comment_id": 93260441, "body": "Maybe take a look at the docs, it might have changed since my answer in 2016. <a href=\"https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#exceptions\" rel=\"nofollow noreferrer\">github.com/kotlintest/kotlintest/blob/master/doc/&hellip;</a>"}], "tags": [], "owner": {"reputation": 14965, "user_id": 2048448, "user_type": "registered", "accept_rate": 82, "profile_image": "https://www.gravatar.com/avatar/9875a5906274bc61f9e3106537a601fc?s=128&d=identicon&r=PG", "display_name": "sksamuel", "link": "https://stackoverflow.com/users/2048448/sksamuel"}, "is_accepted": false, "score": 16, "last_activity_date": 1552409337, "last_edit_date": 1552409337, "creation_date": 1463059777, "answer_id": 37188436, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/37188436#37188436", "title": "Test expected exceptions in Kotlin", "body": "<p>You can use <a href=\"https://github.com/kotlintest/kotlintest\" rel=\"noreferrer\">KotlinTest</a> for this.</p>\n\n<p>In your test, you can wrap arbitary code with a shouldThrow block:</p>\n\n<pre><code>shouldThrow&lt;ArithmeticException&gt; {\n  // code in here that you expect to throw a ArithmeticException\n}\n</code></pre>\n"}, {"tags": [], "owner": {"reputation": 131, "user_id": 1333530, "user_type": "registered", "profile_image": "https://i.stack.imgur.com/kKE1z.jpg?s=128&g=1", "display_name": "Majid", "link": "https://stackoverflow.com/users/1333530/majid"}, "is_accepted": false, "score": 13, "last_activity_date": 1522348072, "creation_date": 1522348072, "answer_id": 49562821, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/49562821#49562821", "title": "Test expected exceptions in Kotlin", "body": "<p>You can also use generics with kotlin.test package:</p>\n\n<pre><code>import kotlin.test.assertFailsWith \n\n@Test\nfun testFunction() {\n    assertFailsWith&lt;MyException&gt; {\n         // The code that will throw MyException\n    }\n}\n</code></pre>\n"}, {"comments": [{"owner": {"reputation": 1944, "user_id": 5844686, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/bdc03955e4050fc063d6593d6e1c8b8a?s=128&d=identicon&r=PG&f=1", "display_name": "Big Pumpkin", "link": "https://stackoverflow.com/users/5844686/big-pumpkin"}, "edited": false, "score": 3, "creation_date": 1575868939, "post_id": 51444821, "comment_id": 104696645, "body": "This is my preferred answer. If you get <code>Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6</code> on assertThrows, make sure your build.gradle has <code>compileTestKotlin {   kotlinOptions.jvmTarget = &quot;1.8&quot; }</code>"}], "tags": [], "owner": {"reputation": 2365, "user_id": 4774054, "user_type": "registered", "accept_rate": 0, "profile_image": "https://i.stack.imgur.com/LRst1.jpg?s=128&g=1", "display_name": "Frank Neblung", "link": "https://stackoverflow.com/users/4774054/frank-neblung"}, "is_accepted": false, "score": 14, "last_activity_date": 1575577806, "last_edit_date": 1575577806, "creation_date": 1532097022, "answer_id": 51444821, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/51444821#51444821", "title": "Test expected exceptions in Kotlin", "body": "<p>JUnit5 has <a href=\"https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions-kotlin\" rel=\"noreferrer\">kotlin support</a> built in.</p>\n\n<pre><code>import org.junit.jupiter.api.Test\nimport org.junit.jupiter.api.assertThrows\n\nclass MyTests {\n    @Test\n    fun `division by zero -- should throw ArithmeticException`() {\n        assertThrows&lt;ArithmeticException&gt; {  1 / 0 }\n    }\n}\n</code></pre>\n"}, {"tags": [], "owner": {"reputation": 528, "user_id": 2769638, "user_type": "registered", "accept_rate": 64, "profile_image": "https://www.gravatar.com/avatar/ef5c9dbac92f669a0f646f5262b7d18b?s=128&d=identicon&r=PG&f=1", "display_name": "alexlz", "link": "https://stackoverflow.com/users/2769638/alexlz"}, "is_accepted": false, "score": 0, "last_activity_date": 1581605632, "creation_date": 1581605632, "answer_id": 60210609, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/60210609#60210609", "title": "Test expected exceptions in Kotlin", "body": "<p>Another version of syntaxis using <a href=\"https://github.com/MarkusAmshove/Kluent\" rel=\"nofollow noreferrer\">kluent</a>:</p>\n\n<pre><code>@Test\nfun `should throw ArithmeticException`() {\n    invoking {\n        val backHole = 1 / 0\n    } `should throw` ArithmeticException::class\n}\n</code></pre>\n"}, {"tags": [], "owner": {"reputation": 249, "user_id": 4940838, "user_type": "registered", "accept_rate": 40, "profile_image": "https://graph.facebook.com/10206662966672757/picture?type=large", "display_name": "Yanay Hollander", "link": "https://stackoverflow.com/users/4940838/yanay-hollander"}, "is_accepted": false, "score": 1, "last_activity_date": 1588837130, "creation_date": 1588837130, "answer_id": 61652292, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/61652292#61652292", "title": "Test expected exceptions in Kotlin", "body": "<p>Assert extension that verifies the exception class and also if the error message match.</p>\n\n<pre><code>inline fun &lt;reified T : Exception&gt; assertThrows(runnable: () -&gt; Any?, message: String?) {\ntry {\n    runnable.invoke()\n} catch (e: Throwable) {\n    if (e is T) {\n        message?.let {\n            Assert.assertEquals(it, \"${e.message}\")\n        }\n        return\n    }\n    Assert.fail(\"expected ${T::class.qualifiedName} but caught \" +\n            \"${e::class.qualifiedName} instead\")\n}\nAssert.fail(\"expected ${T::class.qualifiedName}\")\n</code></pre>\n\n<p>}</p>\n\n<p>for example:</p>\n\n<pre><code>assertThrows&lt;IllegalStateException&gt;({\n        throw IllegalStateException(\"fake error message\")\n    }, \"fake error message\")\n</code></pre>\n"}, {"tags": [], "owner": {"reputation": 7300, "user_id": 3240381, "user_type": "registered", "accept_rate": 74, "profile_image": "https://i.stack.imgur.com/n4mkr.png?s=128&g=1", "display_name": "Cabezas", "link": "https://stackoverflow.com/users/3240381/cabezas"}, "is_accepted": false, "score": 0, "last_activity_date": 1597748401, "last_edit_date": 1597748401, "creation_date": 1597747958, "answer_id": 63467093, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/63467093#63467093", "title": "Test expected exceptions in Kotlin", "body": "<p>Firt steps is to add <code>(expected = YourException::class)</code> in test annotation</p>\n<pre><code>@Test(expected = YourException::class)\n</code></pre>\n<p>Second step is to add this function</p>\n<pre><code>private fun throwException(): Boolean = throw YourException()\n</code></pre>\n<p>Finally you will have something like this:</p>\n<pre><code>@Test(expected = ArithmeticException::class)\nfun `get query error from assets`() {\n    //Given\n    val error = &quot;ArithmeticException&quot;\n\n    //When\n    throwException()\n    val result =  omg()\n\n    //Then\n    Assert.assertEquals(result, error)\n}\nprivate fun throwException(): Boolean = throw ArithmeticException()\n</code></pre>\n"}, {"tags": [], "owner": {"reputation": 17453, "user_id": 5279996, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/cf8327567575d69a46bd8afe8db4466e?s=128&d=identicon&r=PG", "display_name": "Braian Coronel", "link": "https://stackoverflow.com/users/5279996/braian-coronel"}, "is_accepted": false, "score": 0, "last_activity_date": 1601462852, "creation_date": 1601462852, "answer_id": 64135976, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/64135976#64135976", "title": "Test expected exceptions in Kotlin", "body": "<h2>org.junit.jupiter.api.Assertions.kt</h2>\n<pre><code>/**\n * Example usage:\n * ```kotlin\n * val exception = assertThrows&lt;IllegalArgumentException&gt;(&quot;Should throw an Exception&quot;) {\n *     throw IllegalArgumentException(&quot;Talk to a duck&quot;)\n * }\n * assertEquals(&quot;Talk to a duck&quot;, exception.message)\n * ```\n * @see Assertions.assertThrows\n */\ninline fun &lt;reified T : Throwable&gt; assertThrows(message: String, noinline executable: () -&gt; Unit): T =\n        assertThrows({ message }, executable)\n</code></pre>\n"}, {"tags": [], "owner": {"reputation": 167, "user_id": 7130507, "user_type": "registered", "profile_image": "https://i.stack.imgur.com/rTbqy.jpg?s=128&g=1", "display_name": "Svetopolk", "link": "https://stackoverflow.com/users/7130507/svetopolk"}, "is_accepted": false, "score": 2, "last_activity_date": 1602073990, "creation_date": 1602073990, "answer_id": 64244122, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin/64244122#64244122", "title": "Test expected exceptions in Kotlin", "body": "<p>Nobody mentioned that assertFailsWith() returns the value and you can check exception attributes:</p>\n<pre><code>@Test\nfun `my test`() {\n        val exception = assertFailsWith&lt;MyException&gt; {method()}\n        assertThat(exception.message, equalTo(&quot;oops!&quot;))\n    }\n}\n</code></pre>\n"}], "owner": {"reputation": 235985, "user_id": 252000, "user_type": "registered", "accept_rate": 95, "profile_image": "https://www.gravatar.com/avatar/082b8ee2b0aebb430b8d4d98e6a5c32f?s=128&d=identicon&r=PG", "display_name": "fredoverflow", "link": "https://stackoverflow.com/users/252000/fredoverflow"}, "delete_vote_count": 0, "reopen_vote_count": 0, "close_vote_count": 0, "is_answered": true, "view_count": 47105, "favorite_count": 9, "accepted_answer_id": 30575351, "answer_count": 11, "score": 101, "last_activity_date": 1602793065, "creation_date": 1432054887, "last_edit_date": 1602793065, "question_id": 30331806, "link": "https://stackoverflow.com/questions/30331806/test-expected-exceptions-in-kotlin", "title": "Test expected exceptions in Kotlin", "body": "<p>In Java, the programmer can specify expected exceptions for JUnit test cases like this:</p>\n<pre><code>@Test(expected = ArithmeticException.class)\npublic void omg()\n{\n    int blackHole = 1 / 0;\n}\n</code></pre>\n<p>How would I do this in Kotlin? I have tried two syntax variations, but none of them worked:</p>\n<pre><code>import org.junit.Test\n\n// ...\n\n@Test(expected = ArithmeticException) fun omg()\n    Please specify constructor invocation;\n    classifier 'ArithmeticException' does not have a companion object\n\n@Test(expected = ArithmeticException.class) fun omg()\n                            name expected ^\n                                            ^ expected ')'\n</code></pre>\n"}, {"tags": ["java", "mocking", "mockito", "kotlin"], "comments": [{"owner": {"reputation": 5491, "user_id": 1439771, "user_type": "registered", "accept_rate": 75, "profile_image": "https://i.stack.imgur.com/egtxg.png?s=128&g=1", "display_name": "SimY4", "link": "https://stackoverflow.com/users/1439771/simy4"}, "edited": false, "score": 2, "creation_date": 1431958603, "post_id": 30305217, "comment_id": 48706532, "body": "There&#39;s a discussion on a kotlin community site on how to avoid this problem, check it out: <a href=\"https://devnet.jetbrains.com/thread/443551\" rel=\"nofollow noreferrer\">devnet.jetbrains.com/thread/443551</a>"}, {"owner": {"reputation": 5483, "user_id": 1356130, "user_type": "registered", "accept_rate": 85, "profile_image": "https://www.gravatar.com/avatar/71a884fac9d80ee3171a4018b1eaf660?s=128&d=identicon&r=PG", "display_name": "atok", "link": "https://stackoverflow.com/users/1356130/atok"}, "reply_to_user": {"reputation": 5491, "user_id": 1439771, "user_type": "registered", "accept_rate": 75, "profile_image": "https://i.stack.imgur.com/egtxg.png?s=128&g=1", "display_name": "SimY4", "link": "https://stackoverflow.com/users/1439771/simy4"}, "edited": false, "score": 1, "creation_date": 1431959440, "post_id": 30305217, "comment_id": 48707183, "body": "Thank you. Seems like devnet.jetbrains.com is not very well indexed by google."}], "answers": [{"comments": [{"owner": {"reputation": 14221, "user_id": 1212960, "user_type": "registered", "accept_rate": 93, "profile_image": "https://www.gravatar.com/avatar/b3f39c683b5fbe30dfed80b8782d0195?s=128&d=identicon&r=PG", "display_name": "Greg Kopff", "link": "https://stackoverflow.com/users/1212960/greg-kopff"}, "edited": false, "score": 6, "creation_date": 1431988798, "post_id": 30308199, "comment_id": 48723160, "body": "I believe SO kindly asks that you replicate the content of the link in your answer as well, so that if the link ever goes dead this answer is still useful."}, {"owner": {"reputation": 89682, "user_id": 675383, "user_type": "registered", "accept_rate": 94, "profile_image": "https://www.gravatar.com/avatar/6e7a971eb341ffeaa3efca407239bf3b?s=128&d=identicon&r=PG", "display_name": "nhaarman", "link": "https://stackoverflow.com/users/675383/nhaarman"}, "edited": false, "score": 1, "creation_date": 1451000784, "post_id": 30308199, "comment_id": 56659788, "body": "Sadly, in 1.0.0-beta-4584 this workaround doesn&#39;t seem to work anymore: <code>kotlin.TypeCastException: null cannot be cast to non-null type X</code>."}, {"owner": {"reputation": 4016, "user_id": 1460833, "user_type": "registered", "accept_rate": 75, "profile_image": "https://www.gravatar.com/avatar/bc4821b9c16457694f503b42831198f1?s=128&d=identicon&r=PG", "display_name": "Sergey Mashkov", "link": "https://stackoverflow.com/users/1460833/sergey-mashkov"}, "reply_to_user": {"reputation": 89682, "user_id": 675383, "user_type": "registered", "accept_rate": 94, "profile_image": "https://www.gravatar.com/avatar/6e7a971eb341ffeaa3efca407239bf3b?s=128&d=identicon&r=PG", "display_name": "nhaarman", "link": "https://stackoverflow.com/users/675383/nhaarman"}, "edited": false, "score": 0, "creation_date": 1451303161, "post_id": 30308199, "comment_id": 56727488, "body": "@nhaarman works perfect for me, could you please point me to the exact case?"}, {"owner": {"reputation": 11920, "user_id": 6769908, "user_type": "registered", "accept_rate": 91, "profile_image": "https://i.stack.imgur.com/xCiwB.jpg?s=128&g=1", "display_name": "Amir Ziarati", "link": "https://stackoverflow.com/users/6769908/amir-ziarati"}, "edited": false, "score": 3, "creation_date": 1525421473, "post_id": 30308199, "comment_id": 87357742, "body": "its not working on Kotlin 1.2.40. isnt there any other workaround ?"}, {"owner": {"reputation": 2775, "user_id": 2102748, "user_type": "registered", "accept_rate": 100, "profile_image": "https://www.gravatar.com/avatar/2a1adcb8ed924ecd1045fd6252a7df18?s=128&d=identicon&r=PG", "display_name": "milosmns", "link": "https://stackoverflow.com/users/2102748/milosmns"}, "reply_to_user": {"reputation": 89682, "user_id": 675383, "user_type": "registered", "accept_rate": 94, "profile_image": "https://www.gravatar.com/avatar/6e7a971eb341ffeaa3efca407239bf3b?s=128&d=identicon&r=PG", "display_name": "nhaarman", "link": "https://stackoverflow.com/users/675383/nhaarman"}, "edited": false, "score": 0, "creation_date": 1547217979, "post_id": 30308199, "comment_id": 95128468, "body": "@nhaarman Kotlin 1.3.11, Mockito 2.7.12, Kotlin Mockito 1.5.0, Jan 2019: Workaround 1... well, it works around. My use case is within the given/when clause."}, {"owner": {"reputation": 397, "user_id": 2804473, "user_type": "registered", "accept_rate": 100, "profile_image": "https://i.stack.imgur.com/sp4Vh.jpg?s=128&g=1", "display_name": "Simon Cedergren Malmqvist", "link": "https://stackoverflow.com/users/2804473/simon-cedergren-malmqvist"}, "edited": false, "score": 0, "creation_date": 1578390538, "post_id": 30308199, "comment_id": 105413954, "body": "Mockito.anyObject is marked as deprecated and will be removed in Mockito 3.0 FYI"}], "tags": [], "owner": {"reputation": 4016, "user_id": 1460833, "user_type": "registered", "accept_rate": 75, "profile_image": "https://www.gravatar.com/avatar/bc4821b9c16457694f503b42831198f1?s=128&d=identicon&r=PG", "display_name": "Sergey Mashkov", "link": "https://stackoverflow.com/users/1460833/sergey-mashkov"}, "is_accepted": true, "score": 81, "last_activity_date": 1471816477, "last_edit_date": 1471816477, "creation_date": 1431965798, "answer_id": 30308199, "question_id": 30305217, "link": "https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin/30308199#30308199", "title": "Is it possible to use Mockito in Kotlin?", "body": "<p>There are two possible workarounds:</p>\n\n<pre><code>private fun &lt;T&gt; anyObject(): T {\n    Mockito.anyObject&lt;T&gt;()\n    return uninitialized()\n}\n\nprivate fun &lt;T&gt; uninitialized(): T = null as T\n\n@Test\nfun myTest() {\n    `when`(mockedBackend).login(anyObject())).thenAnswer { ... }\n}\n</code></pre>\n\n<p>The other workaround is </p>\n\n<pre><code>private fun &lt;T&gt; anyObject(): T {\n    return Mockito.anyObject&lt;T&gt;()\n}\n\n@Test\nfun myTest() {\n    `when`(mockedBackend).login(anyObject())).thenAnswer { ... }\n}\n</code></pre>\n\n<p>Here is <a href=\"https://discuss.kotlinlang.org/t/how-to-use-mockito-with-kotlin/324\" rel=\"noreferrer\">some more discussion</a> on this topic, where the workaround is first suggested.</p>\n"}, {"tags": [], "owner": {"reputation": 1620, "user_id": 3497739, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/7fe352a05b70a726f7919d54236b21ef?s=128&d=identicon&r=PG", "display_name": "maxandron", "link": "https://stackoverflow.com/users/3497739/maxandron"}, "is_accepted": false, "score": 10, "last_activity_date": 1457018526, "creation_date": 1457018526, "answer_id": 35776132, "question_id": 30305217, "link": "https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin/35776132#35776132", "title": "Is it possible to use Mockito in Kotlin?", "body": "<p>I use <code>verify</code> a lot to make sure the parameters passed to a function are also correct.</p>\n\n<p>To do this, and still avoid the NPE you can use kotlin's elvis operator.\nfor example:\n<code>verify(mock).func(same(my_obj) ?: my_obj)</code></p>\n\n<p>This way, mockito is satisfied because it actually verifies the variable, and kotlin is satisfied because we pass a non null object.</p>\n\n<p>Another thing I stumbled upon was the mockito-kotlin library which solves exactly this issue\n<a href=\"https://github.com/nhaarman/mockito-kotlin\" rel=\"noreferrer\">https://github.com/nhaarman/mockito-kotlin</a></p>\n"}, {"comments": [{"owner": {"reputation": 452, "user_id": 1227193, "user_type": "registered", "accept_rate": 50, "profile_image": "https://www.gravatar.com/avatar/e98c124c1b9fd4fb4d581a5549753676?s=128&d=identicon&r=PG", "display_name": "Surekha", "link": "https://stackoverflow.com/users/1227193/surekha"}, "edited": false, "score": 2, "creation_date": 1521210109, "post_id": 48091649, "comment_id": 85647196, "body": "Looks like the URL is moved to: <a href=\"https://github.com/googlesamples/android-architecture/blob/todo-mvp-kotlin/todoapp/app/src/test/java/com/example/android/architecture/blueprints/todoapp/MockitoKotlinHelpers.kt\" rel=\"nofollow noreferrer\">github.com/googlesamples/android-architecture/blob/&hellip;</a>"}, {"owner": {"reputation": 1103, "user_id": 7721982, "user_type": "registered", "profile_image": "https://i.stack.imgur.com/x4Cww.png?s=128&g=1", "display_name": "Fatmajk", "link": "https://stackoverflow.com/users/7721982/fatmajk"}, "edited": false, "score": 0, "creation_date": 1593589817, "post_id": 48091649, "comment_id": 110830749, "body": "Great thanks! Works with latest version of Mockito as well (v3.3.3) and Kotlin (v1.3.72)"}], "tags": [], "owner": {"reputation": 4770, "user_id": 1552622, "user_type": "registered", "accept_rate": 60, "profile_image": "https://i.stack.imgur.com/0DBwH.jpg?s=128&g=1", "display_name": "makovkastar", "link": "https://stackoverflow.com/users/1552622/makovkastar"}, "is_accepted": false, "score": 31, "last_activity_date": 1521215801, "last_edit_date": 1521215801, "creation_date": 1515055734, "answer_id": 48091649, "question_id": 30305217, "link": "https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin/48091649#48091649", "title": "Is it possible to use Mockito in Kotlin?", "body": "<p>You can use the following helper functions to use Mockito's any(), eq() and capture() matchers in Kotlin:</p>\n\n<pre><code>/**\n * Returns Mockito.eq() as nullable type to avoid java.lang.IllegalStateException when\n * null is returned.\n *\n * Generic T is nullable because implicitly bounded by Any?.\n */\nfun &lt;T&gt; eq(obj: T): T = Mockito.eq&lt;T&gt;(obj)\n\n/**\n * Returns Mockito.any() as nullable type to avoid java.lang.IllegalStateException when\n * null is returned.\n */\nfun &lt;T&gt; any(): T = Mockito.any&lt;T&gt;()\n\n/**\n * Returns ArgumentCaptor.capture() as nullable type to avoid java.lang.IllegalStateException\n * when null is returned.\n */\nfun &lt;T&gt; capture(argumentCaptor: ArgumentCaptor&lt;T&gt;): T = argumentCaptor.capture()\n</code></pre>\n\n<p>See <a href=\"https://github.com/googlesamples/android-architecture/blob/todo-mvp-kotlin/todoapp/app/src/test/java/com/example/android/architecture/blueprints/todoapp/MockitoKotlinHelpers.kt\" rel=\"noreferrer\">MockitoKotlinHelpers.kt</a> from the Android Architecture Blueprints repository by Google.</p>\n"}, {"comments": [{"owner": {"reputation": 291, "user_id": 4855062, "user_type": "registered", "profile_image": "https://i.stack.imgur.com/duymN.png?s=128&g=1", "display_name": "Thales Pupo Araujo", "link": "https://stackoverflow.com/users/4855062/thales-pupo-araujo"}, "edited": false, "score": 7, "creation_date": 1561999446, "post_id": 48805160, "comment_id": 100231163, "body": "Is possible to avoid passing the <i>ClassName::class.java</i> in argument using the reified args: <code>inline fun &lt;reified T&gt; anyNonNull(): T = Mockito.any&lt;T&gt;(T::class.java)</code>"}], "tags": [], "owner": {"reputation": 924, "user_id": 2545800, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/58ec80904ce1ba59655dd73f781ab4e6?s=128&d=identicon&r=PG", "display_name": "Shamm", "link": "https://stackoverflow.com/users/2545800/shamm"}, "is_accepted": false, "score": 45, "last_activity_date": 1518691086, "creation_date": 1518691086, "answer_id": 48805160, "question_id": 30305217, "link": "https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin/48805160#48805160", "title": "Is it possible to use Mockito in Kotlin?", "body": "<p>For those who need typed <code>any(type: Class&lt;T&gt;)</code></p>\n\n<pre><code>    private fun &lt;T&gt; any(type: Class&lt;T&gt;): T = Mockito.any&lt;T&gt;(type)\n</code></pre>\n\n<p>This would work and the type check also happens!</p>\n"}, {"tags": [], "owner": {"reputation": 21, "user_id": 10550012, "user_type": "registered", "profile_image": "https://lh4.googleusercontent.com/-03BY2G1llOg/AAAAAAAAAAI/AAAAAAAAAAA/ABtNlbC4PL9SzIIYs1eq7ymv0AAbGpnUCg/mo/photo.jpg?sz=128", "display_name": "max li", "link": "https://stackoverflow.com/users/10550012/max-li"}, "is_accepted": false, "score": 2, "last_activity_date": 1591070527, "creation_date": 1591070527, "answer_id": 62144613, "question_id": 30305217, "link": "https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin/62144613#62144613", "title": "Is it possible to use Mockito in Kotlin?", "body": "<p>it just need to return a nonnull result when you use <code>Mockito.any()</code>;</p>\n\n<pre><code>Mockito.any() ?: 0\nMockito.any() ?: HashMap&lt;Int,Int&gt;()\nMockito.any() ?: {}\n</code></pre>\n\n<p>...</p>\n"}, {"tags": [], "owner": {"reputation": 4581, "user_id": 4138919, "user_type": "registered", "accept_rate": 55, "profile_image": "https://www.gravatar.com/avatar/56c8424e58791f536490bbbd629d890d?s=128&d=identicon&r=PG&f=1", "display_name": "VIN", "link": "https://stackoverflow.com/users/4138919/vin"}, "is_accepted": false, "score": 0, "last_activity_date": 1599153470, "creation_date": 1599153470, "answer_id": 63728650, "question_id": 30305217, "link": "https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin/63728650#63728650", "title": "Is it possible to use Mockito in Kotlin?", "body": "<p>To extend on the answer provided by @makovkastar, you can provide a nullable or non-nullable Matcher like this:</p>\n<pre><code>/**\n * Matcher that returns null\n */\nprivate inline fun &lt;reified T&gt; any(): T = Mockito.any&lt;T&gt;()\n\n/**\n * Matcher never returns null\n */\nprivate inline fun &lt;reified T&gt; any(type: Class&lt;T&gt;): T = Mockito.any(type)\n</code></pre>\n"}], "owner": {"reputation": 5483, "user_id": 1356130, "user_type": "registered", "accept_rate": 85, "profile_image": "https://www.gravatar.com/avatar/71a884fac9d80ee3171a4018b1eaf660?s=128&d=identicon&r=PG", "display_name": "atok", "link": "https://stackoverflow.com/users/1356130/atok"}, "delete_vote_count": 0, "reopen_vote_count": 0, "close_vote_count": 0, "is_answered": true, "view_count": 36602, "favorite_count": 18, "accepted_answer_id": 30308199, "answer_count": 6, "score": 85, "last_activity_date": 1599153470, "creation_date": 1431957514, "question_id": 30305217, "link": "https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin", "title": "Is it possible to use Mockito in Kotlin?", "body": "<p>The problem I'm facing is that <code>Matchers.anyObject()</code> returns <code>null</code>. When used to mock method that only accepts non-nullable types it causes a \"Should not be null\" exception to be thrown. </p>\n\n<pre><code>`when`(mockedBackend.login(anyObject())).thenAnswer { invocationOnMock -&gt; someResponse }\n</code></pre>\n\n<p>Mocked method:</p>\n\n<pre><code>public open fun login(userCredentials: UserCredentials): Response\n</code></pre>\n"}, {"tags": ["android", "testing", "android-espresso", "kotlin"], "answers": [{"tags": [], "owner": {"reputation": 4482, "user_id": 4879701, "user_type": "registered", "profile_image": "https://i.stack.imgur.com/i8P8G.jpg?s=128&g=1", "display_name": "Be_Negative", "link": "https://stackoverflow.com/users/4879701/be-negative"}, "is_accepted": true, "score": 11, "last_activity_date": 1511187651, "last_edit_date": 1511187651, "creation_date": 1431704603, "answer_id": 30263595, "question_id": 30261962, "link": "https://stackoverflow.com/questions/30261962/activitytestrule-getactivity-returns-null-in-before-method/30263595#30263595", "title": "ActivityTestRule.getActivity returns null in Before method", "body": "<p>You can get the production app context from <code>InstrumentationRegistry</code> like so:\n<code>InstrumentationRegistry.getTargetContext()</code></p>\n\n<p>Keep in mind that: <code>InstrumentationRegistry.getContext()</code> is the context of your test apk.</p>\n"}, {"comments": [{"owner": {"reputation": 2143, "user_id": 2949834, "user_type": "registered", "accept_rate": 80, "profile_image": "https://i.stack.imgur.com/LikXg.png?s=128&g=1", "display_name": "kimkevin", "link": "https://stackoverflow.com/users/2949834/kimkevin"}, "edited": false, "score": 0, "creation_date": 1566205445, "post_id": 54928875, "comment_id": 101569165, "body": "androidx.test.InstrumentationRegistry is deprecated. using androidx.test.platform.app.InstrumentationRegistry."}], "tags": [], "owner": {"reputation": 2237, "user_id": 1087449, "user_type": "registered", "accept_rate": 29, "profile_image": "https://www.gravatar.com/avatar/c716b253577b0562c355b3797a5e1a2e?s=128&d=identicon&r=PG", "display_name": "giorgos.nl", "link": "https://stackoverflow.com/users/1087449/giorgos-nl"}, "is_accepted": false, "score": -1, "last_activity_date": 1551366995, "creation_date": 1551366995, "answer_id": 54928875, "question_id": 30261962, "link": "https://stackoverflow.com/questions/30261962/activitytestrule-getactivity-returns-null-in-before-method/54928875#54928875", "title": "ActivityTestRule.getActivity returns null in Before method", "body": "<p>At the moment of writing, <code>InstrumentationRegistry</code> is deprecated.\nI use <code>ApplicationProvider.getApplicationContext&lt;Application&gt;()</code> from <code>androidx.test</code> library instead.</p>\n\n<p>The dependency is: <code>androidTestImplementation \"androidx.test.espresso:espresso-core:3.1.1\"</code></p>\n"}], "owner": {"reputation": 5143, "user_id": 600351, "user_type": "registered", "accept_rate": 60, "profile_image": "https://www.gravatar.com/avatar/7a2a3b9fd62972fa271deb3d0e31256c?s=128&d=identicon&r=PG", "display_name": "Geob-o-matic", "link": "https://stackoverflow.com/users/600351/geob-o-matic"}, "delete_vote_count": 0, "reopen_vote_count": 0, "close_vote_count": 0, "is_answered": true, "view_count": 2822, "favorite_count": 0, "accepted_answer_id": 30263595, "answer_count": 2, "score": 4, "last_activity_date": 1551366995, "creation_date": 1431699867, "question_id": 30261962, "link": "https://stackoverflow.com/questions/30261962/activitytestrule-getactivity-returns-null-in-before-method", "title": "ActivityTestRule.getActivity returns null in Before method", "body": "<p>I need to empty my user's data before each test</p>\n\n<pre><code>// Kotlin code\nfun getActivity() = activityRule.getActivity()\n\nBefore\nfun setUp() {\n    cleanUp(getActivity())\n}\n</code></pre>\n\n<p>I need to get a Context in order to do so, but in setUp, activityRule.getActivity() returns null.</p>\n\n<p>I also tried:</p>\n\n<pre><code>Before\nfun setUp() {\n    val i = Intent()\n    i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)\n    activityRule.lauchActivity(i)\n    cleanUp(getActivity())\n}\n</code></pre>\n\n<p>I got an activity, but cleanUp works only half of the time (I believe some race condition apply here)</p>\n\n<p>I want to avoid to cleanUp in an After function in order to see manually my app state if needed.</p>\n\n<p>Is there anyway to get a context in a Before function?</p>\n\n<p>Thanks</p>\n"}]